"""initial_schema

Revision ID: 05ecbb7b2bc1
Revises: 
Create Date: 2026-06-01 13:23:44.613765
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '05ecbb7b2bc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('performed_by', sa.String(length=255), nullable=True),
    sa.Column('old_data', sa.Text(), nullable=True),
    sa.Column('new_data', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('audit_id'),
    schema='audit'
    )
    op.create_table('healthcare_professionals',
    sa.Column('professional_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('professional_license', sa.String(length=100), nullable=True),
    sa.Column('specialty', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('professional_uuid'),
    schema='clinical'
    )
    op.create_table('education_levels',
    sa.Column('education_level_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('education_level_id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('ethnicities',
    sa.Column('ethnicity_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('ethnicity_id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('gender_identities',
    sa.Column('gender_identity_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('gender_identity_id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('sex_types',
    sa.Column('sex_type_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('sex_type_id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('assessment_scales',
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('scale_name', sa.String(length=255), nullable=False),
    sa.Column('scale_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('scale_id'),
    sa.UniqueConstraint('scale_name'),
    schema='diagnostic'
    )
    op.create_table('disorders',
    sa.Column('disorder_id', sa.Integer(), nullable=False),
    sa.Column('cid_code', sa.String(length=20), nullable=True),
    sa.Column('dsm_code', sa.String(length=20), nullable=True),
    sa.Column('disorder_name', sa.String(length=255), nullable=False),
    sa.Column('disorder_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('disorder_id'),
    sa.UniqueConstraint('disorder_name'),
    schema='diagnostic'
    )
    op.create_table('symptoms',
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('symptom_name', sa.String(length=255), nullable=False),
    sa.Column('symptom_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('symptom_id'),
    sa.UniqueConstraint('symptom_name'),
    schema='diagnostic'
    )
    op.create_table('patient_identity',
    sa.Column('patient_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('cpf_hash', sa.String(length=255), nullable=True),
    sa.Column('email_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('patient_uuid'),
    schema='security'
    )
    op.create_table('users',
    sa.Column('user_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email_hash', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='clinician', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_uuid'),
    sa.UniqueConstraint('username'),
    schema='security'
    )
    op.create_table('patient_profile',
    sa.Column('profile_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_uuid', sa.UUID(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex_type_id', sa.Integer(), nullable=True),
    sa.Column('gender_identity_id', sa.Integer(), nullable=True),
    sa.Column('education_level_id', sa.Integer(), nullable=True),
    sa.Column('ethnicity_id', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['education_level_id'], ['core.education_levels.education_level_id'], ),
    sa.ForeignKeyConstraint(['ethnicity_id'], ['core.ethnicities.ethnicity_id'], ),
    sa.ForeignKeyConstraint(['gender_identity_id'], ['core.gender_identities.gender_identity_id'], ),
    sa.ForeignKeyConstraint(['patient_uuid'], ['security.patient_identity.patient_uuid'], ),
    sa.ForeignKeyConstraint(['sex_type_id'], ['core.sex_types.sex_type_id'], ),
    sa.PrimaryKeyConstraint('profile_uuid'),
    sa.UniqueConstraint('patient_uuid'),
    schema='clinical'
    )
    op.create_table('diagnosis_relationships',
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('source_disorder_id', sa.Integer(), nullable=False),
    sa.Column('target_disorder_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('relationship_weight', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('clinical_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_disorder_id'], ['diagnostic.disorders.disorder_id'], ),
    sa.ForeignKeyConstraint(['target_disorder_id'], ['diagnostic.disorders.disorder_id'], ),
    sa.PrimaryKeyConstraint('relationship_id'),
    schema='diagnostic'
    )
    op.create_table('diagnostic_criteria',
    sa.Column('criteria_id', sa.Integer(), nullable=False),
    sa.Column('disorder_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('required_presence', sa.Boolean(), nullable=True),
    sa.Column('minimum_duration_days', sa.Integer(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['disorder_id'], ['diagnostic.disorders.disorder_id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['diagnostic.symptoms.symptom_id'], ),
    sa.PrimaryKeyConstraint('criteria_id'),
    schema='diagnostic'
    )
    op.create_table('scale_questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['scale_id'], ['diagnostic.assessment_scales.scale_id'], ),
    sa.PrimaryKeyConstraint('question_id'),
    schema='diagnostic'
    )
    op.create_table('bayesian_relationships',
    sa.Column('bayesian_relationship_id', sa.Integer(), nullable=False),
    sa.Column('disorder_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('prior_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('posterior_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('likelihood_ratio', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disorder_id'], ['diagnostic.disorders.disorder_id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['diagnostic.symptoms.symptom_id'], ),
    sa.PrimaryKeyConstraint('bayesian_relationship_id'),
    schema='ml'
    )
    op.create_table('probabilistic_feature_weights',
    sa.Column('weight_id', sa.Integer(), nullable=False),
    sa.Column('disorder_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('feature_weight', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['disorder_id'], ['diagnostic.disorders.disorder_id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['diagnostic.symptoms.symptom_id'], ),
    sa.PrimaryKeyConstraint('weight_id'),
    schema='ml'
    )
    op.create_table('clinical_consultation',
    sa.Column('consultation_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_uuid', sa.UUID(), nullable=False),
    sa.Column('professional_uuid', sa.UUID(), nullable=True),
    sa.Column('consultation_date', sa.DateTime(), nullable=False),
    sa.Column('consultation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['professional_uuid'], ['clinical.healthcare_professionals.professional_uuid'], ),
    sa.ForeignKeyConstraint(['profile_uuid'], ['clinical.patient_profile.profile_uuid'], ),
    sa.PrimaryKeyConstraint('consultation_uuid'),
    schema='clinical'
    )
    op.create_table('clinical_episode',
    sa.Column('episode_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('profile_uuid', sa.UUID(), nullable=False),
    sa.Column('episode_start', sa.DateTime(), nullable=True),
    sa.Column('episode_end', sa.DateTime(), nullable=True),
    sa.Column('episode_type', sa.String(length=100), nullable=True),
    sa.Column('clinical_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_uuid'], ['clinical.patient_profile.profile_uuid'], ),
    sa.PrimaryKeyConstraint('episode_uuid'),
    schema='clinical'
    )
    op.create_table('scale_responses',
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('consultation_uuid', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_uuid'], ['clinical.clinical_consultation.consultation_uuid'], ),
    sa.ForeignKeyConstraint(['question_id'], ['diagnostic.scale_questions.question_id'], ),
    sa.PrimaryKeyConstraint('response_id'),
    schema='clinical'
    )
    op.create_table('symptom_observation',
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('consultation_uuid', sa.UUID(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('intensity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_uuid'], ['clinical.clinical_consultation.consultation_uuid'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['diagnostic.symptoms.symptom_id'], ),
    sa.PrimaryKeyConstraint('observation_id'),
    schema='clinical'
    )
    op.create_table('diagnostic_inference',
    sa.Column('inference_uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('consultation_uuid', sa.UUID(), nullable=False),
    sa.Column('disorder_id', sa.Integer(), nullable=False),
    sa.Column('inference_probability', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('generated_by_model', sa.String(length=120), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['consultation_uuid'], ['clinical.clinical_consultation.consultation_uuid'], ),
    sa.ForeignKeyConstraint(['disorder_id'], ['diagnostic.disorders.disorder_id'], ),
    sa.PrimaryKeyConstraint('inference_uuid'),
    schema='diagnostic'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic_inference', schema='diagnostic')
    op.drop_table('symptom_observation', schema='clinical')
    op.drop_table('scale_responses', schema='clinical')
    op.drop_table('clinical_episode', schema='clinical')
    op.drop_table('clinical_consultation', schema='clinical')
    op.drop_table('probabilistic_feature_weights', schema='ml')
    op.drop_table('bayesian_relationships', schema='ml')
    op.drop_table('scale_questions', schema='diagnostic')
    op.drop_table('diagnostic_criteria', schema='diagnostic')
    op.drop_table('diagnosis_relationships', schema='diagnostic')
    op.drop_table('patient_profile', schema='clinical')
    op.drop_table('users', schema='security')
    op.drop_table('patient_identity', schema='security')
    op.drop_table('symptoms', schema='diagnostic')
    op.drop_table('disorders', schema='diagnostic')
    op.drop_table('assessment_scales', schema='diagnostic')
    op.drop_table('sex_types', schema='core')
    op.drop_table('gender_identities', schema='core')
    op.drop_table('ethnicities', schema='core')
    op.drop_table('education_levels', schema='core')
    op.drop_table('healthcare_professionals', schema='clinical')
    op.drop_table('audit_logs', schema='audit')
    # ### end Alembic commands ###
