"""DSM-5-TR complete disorder catalog — all ~157 disorders across 22 chapters.

Each entry: (portuguese_name, cid10_code, dsm5_code, chapter, description)
Used by db/seed.py to populate the disorder catalog.
The first 19 entries (core disorders) have full clinical pipeline support.
"""

DSM5TR_DISORDERS = [
    # ── Chapter 1: Transtornos do Neurodesenvolvimento ──
    ("Deficiência Intelectual", "F70", "317", "Transtornos do Neurodesenvolvimento", "Déficit significativo nas funções intelectuais e adaptativas com início no período do desenvolvimento.", False),
    ("Deficiência Intelectual Leve", "F70", "317", "Transtornos do Neurodesenvolvimento", "Forma leve de deficiência intelectual com QI aproximadamente entre 50-70.", False),
    ("Deficiência Intelectual Moderada", "F71", "318.0", "Transtornos do Neurodesenvolvimento", "Forma moderada com QI aproximadamente entre 35-49.", False),
    ("Deficiência Intelectual Grave", "F72", "318.1", "Transtornos do Neurodesenvolvimento", "Forma grave com QI aproximadamente entre 20-34.", False),
    ("Deficiência Intelectual Profunda", "F73", "318.2", "Transtornos do Neurodesenvolvimento", "Forma profunda com QI abaixo de 20.", False),
    ("Atraso Global do Desenvolvimento", "F88", "315.8", "Transtornos do Neurodesenvolvimento", "Atraso em múltiplas áreas do desenvolvimento em crianças menores de 5 anos.", False),
    ("Deficiência Intelectual Não Especificada", "F79", "319", "Transtornos do Neurodesenvolvimento", "Deficiência intelectual sem especificação de gravidade.", False),
    ("Transtorno da Linguagem", "F80.2", "315.32", "Transtornos do Neurodesenvolvimento", "Déficits persistentes na aquisição e uso da linguagem em todas as modalidades.", False),
    ("Transtorno Fonológico", "F80.0", "315.39", "Transtornos do Neurodesenvolvimento", "Dificuldade persistente na produção de sons da fala.", False),
    ("Transtorno da Fluência com Início na Infância (Gagueira)", "F80.81", "315.35", "Transtornos do Neurodesenvolvimento", "Alterações na fluência e padrão temporal da fala inadequadas para a idade.", False),
    ("Transtorno da Comunicação Social (Pragmática)", "F80.89", "315.39", "Transtornos do Neurodesenvolvimento", "Déficits no uso social da comunicação verbal e não verbal.", False),
    ("Transtorno da Comunicação Não Especificado", "F80.9", "315.39", "Transtornos do Neurodesenvolvimento", "Sintomas de transtorno da comunicação que não preenchem critérios completos.", False),
    ("Transtorno do Espectro Autista", "F84.0", "299.00", "Transtornos do Neurodesenvolvimento", "Déficits persistentes na comunicação social e interação social, com padrões restritos e repetitivos de comportamento.", True),
    ("Transtorno de Déficit de Atenção/Hiperatividade", "F90.0", "314.01", "Transtornos do Neurodesenvolvimento", "Padrão persistente de desatenção e/ou hiperatividade-impulsividade que interfere no funcionamento.", True),
    ("Transtorno de Déficit de Atenção/Hiperatividade — Apresentação Combinada", "F90.2", "314.01", "Transtornos do Neurodesenvolvimento", "TDAH com sintomas tanto de desatenção quanto de hiperatividade-impulsividade.", False),
    ("Transtorno de Déficit de Atenção/Hiperatividade — Apresentação Predominante com Desatenção", "F90.0", "314.00", "Transtornos do Neurodesenvolvimento", "TDAH com predomínio de sintomas de desatenção.", False),
    ("Transtorno de Déficit de Atenção/Hiperatividade — Apresentação Predominante com Hiperatividade", "F90.1", "314.01", "Transtornos do Neurodesenvolvimento", "TDAH com predomínio de sintomas de hiperatividade-impulsividade.", False),
    ("Transtorno de Déficit de Atenção/Hiperatividade — Outra Apresentação Especificada", "F90.8", "314.01", "Transtornos do Neurodesenvolvimento", "TDAH com outra apresentação especificada.", False),
    ("Transtorno de Déficit de Atenção/Hiperatividade Não Especificado", "F90.9", "314.01", "Transtornos do Neurodesenvolvimento", "Sintomas de TDAH que não preenchem critérios completos.", False),
    ("Transtorno Específico da Aprendizagem — com Prejuízo na Leitura", "F81.0", "315.00", "Transtornos do Neurodesenvolvimento", "Dificuldades persistentes na leitura (dislexia).", False),
    ("Transtorno Específico da Aprendizagem — com Prejuízo na Expressão Escrita", "F81.81", "315.2", "Transtornos do Neurodesenvolvimento", "Dificuldades persistentes na expressão escrita (disgrafia).", False),
    ("Transtorno Específico da Aprendizagem — com Prejuízo na Matemática", "F81.2", "315.1", "Transtornos do Neurodesenvolvimento", "Dificuldades persistentes na matemática (discalculia).", False),
    ("Transtorno Específico da Aprendizagem Não Especificado", "F81.9", "315.9", "Transtornos do Neurodesenvolvimento", "Dificuldades de aprendizagem que não preenchem critérios completos.", False),
    ("Transtorno do Desenvolvimento da Coordenação", "F82", "315.4", "Transtornos do Neurodesenvolvimento", "Déficit na aquisição e execução de habilidades motoras coordenadas.", False),
    ("Transtorno do Movimento Estereotipado", "F98.4", "307.3", "Transtornos do Neurodesenvolvimento", "Comportamento motor repetitivo, aparentemente impulsivo e não funcional.", False),
    ("Transtorno de Tourette", "F95.2", "307.23", "Transtornos do Neurodesenvolvimento", "Múltiplos tiques motores e um ou mais tiques vocais.", False),
    ("Transtorno de Tique Motor ou Vocal Crônico", "F95.1", "307.22", "Transtornos do Neurodesenvolvimento", "Tiques motores ou vocais únicos ou múltiplos (mas não ambos).", False),
    ("Transtorno de Tique Transitório", "F95.0", "307.21", "Transtornos do Neurodesenvolvimento", "Tiques motores e/ou vocais presentes há menos de 1 ano.", False),
    ("Transtorno de Tique Especificado", "F95.8", "307.20", "Transtornos do Neurodesenvolvimento", "Sintomas de tique que não preenchem critérios completos.", False),
    ("Transtorno de Tique Não Especificado", "F95.9", "307.20", "Transtornos do Neurodesenvolvimento", "Tique sem especificação.", False),
    ("Outro Transtorno do Neurodesenvolvimento Especificado", "F88", "315.8", "Transtornos do Neurodesenvolvimento", "Sintomas de transtorno do neurodesenvolvimento que não preenchem critérios completos.", False),
    ("Transtorno do Neurodesenvolvimento Não Especificado", "F89", "315.9", "Transtornos do Neurodesenvolvimento", "Transtorno do neurodesenvolvimento sem especificação.", False),

    # ── Chapter 2: Espectro da Esquizofrenia e Outros Transtornos Psicóticos ──
    ("Transtorno Delirante", "F22", "297.1", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Presença de um ou mais delírios com duração de 1 mês ou mais.", False),
    ("Transtorno Psicótico Breve", "F23", "298.8", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Sintomas psicóticos com duração entre 1 dia e 1 mês.", False),
    ("Transtorno Esquizofreniforme", "F20.81", "295.40", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Sintomas esquizofrênicos com duração entre 1 e 6 meses.", False),
    ("Esquizofrenia / Transtorno Psicótico", "F20.9", "295.9", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Anormalidades em um ou mais domínios: delírios, alucinações, discurso desorganizado, comportamento desorganizado, sintomas negativos.", True),
    ("Transtorno Esquizoafetivo", "F25.0", "295.70", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Período ininterrupto de doença com episódio de humor maior e sintomas esquizofrênicos.", False),
    ("Transtorno Psicótico Induzido por Substância", "F19.159", "292.9", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Delírios ou alucinações devido aos efeitos de uma substância.", False),
    ("Transtorno Psicótico Devido a Outra Condição Médica", "F06.2", "293.81", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Delírios ou alucinações consequência direta de outra condição médica.", False),
    ("Catatonia Associada a Transtorno Mental", "F06.1", "293.89", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Marcada perturbação psicomotora associada a transtorno mental.", False),
    ("Catatonia Devido a Outra Condição Médica", "F06.1", "293.89", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Catatonia consequência direta de outra condição médica.", False),
    ("Catatonia Não Especificada", "R41.89", "293.89", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Sintomas catatônicos sem especificação clara da causa.", False),
    ("Outro Transtorno do Espectro da Esquizofrenia Especificado", "F28", "298.9", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Sintomas psicóticos que não preenchem critérios completos.", False),
    ("Transtorno do Espectro da Esquizofrenia Não Especificado", "F29", "298.9", "Espectro da Esquizofrenia e Outros Transtornos Psicóticos", "Transtorno psicótico sem especificação.", False),

    # ── Chapter 3: Transtornos Bipolares e Relacionados ──
    ("Transtorno Bipolar Tipo I", "F31.9", "296.7", "Transtornos Bipolares e Relacionados", "Pelo menos um episódio maníaco, geralmente com episódios depressivos maiores.", True),
    ("Transtorno Bipolar Tipo II", "F31.8", "296.89", "Transtornos Bipolares e Relacionados", "Pelo menos um episódio hipomaníaco e um episódio depressivo maior, sem episódio maníaco.", True),
    ("Transtorno Ciclotímico", "F34.0", "301.13", "Transtornos Bipolares e Relacionados", "Numerosos períodos de sintomas hipomaníacos e depressivos subclínicos por pelo menos 2 anos.", False),
    ("Transtorno Bipolar Induzido por Substância", "F19.14", "292.84", "Transtornos Bipolares e Relacionados", "Elevação ou irritabilidade do humor devido aos efeitos de uma substância.", False),
    ("Transtorno Bipolar Devido a Outra Condição Médica", "F06.33", "293.83", "Transtornos Bipolares e Relacionados", "Elevação ou irritabilidade do humor consequência de outra condição médica.", False),
    ("Outro Transtorno Bipolar Especificado", "F31.89", "296.89", "Transtornos Bipolares e Relacionados", "Sintomas bipolares que não preenchem critérios completos.", False),
    ("Transtorno Bipolar Não Especificado", "F31.9", "296.80", "Transtornos Bipolares e Relacionados", "Sintomas bipolares sem especificação.", False),

    # ── Chapter 4: Transtornos Depressivos ──
    ("Transtorno Disruptivo da Desregulação do Humor", "F34.8", "296.99", "Transtornos Depressivos", "Irritabilidade crônica severa e explosões de raiva em crianças de 6-18 anos.", False),
    ("Transtorno Depressivo Maior", "F32.9", "296.22", "Transtornos Depressivos", "Humor deprimido e/ou perda de interesse ou prazer por pelo menos 2 semanas.", True),
    ("Transtorno Depressivo Persistente (Distimia)", "F34.1", "300.4", "Transtornos Depressivos", "Humor deprimido crônico por pelo menos 2 anos com sintomas menos severos que o TDM.", True),
    ("Transtorno Disfórico Pré-Menstrual", "N94.3", "625.4", "Transtornos Depressivos", "Labilidade afetiva, irritabilidade e sintomas depressivos na fase lútea do ciclo menstrual.", False),
    ("Transtorno Depressivo Induzido por Substância", "F19.14", "292.84", "Transtornos Depressivos", "Sintomas depressivos devido aos efeitos de uma substância.", False),
    ("Transtorno Depressivo Devido a Outra Condição Médica", "F06.32", "293.83", "Transtornos Depressivos", "Sintomas depressivos consequência de outra condição médica.", False),
    ("Outro Transtorno Depressivo Especificado", "F32.89", "311", "Transtornos Depressivos", "Sintomas depressivos que não preenchem critérios completos.", False),
    ("Transtorno Depressivo Não Especificado", "F32.9", "311", "Transtornos Depressivos", "Sintomas depressivos sem especificação.", False),

    # ── Chapter 5: Transtornos de Ansiedade ──
    ("Transtorno de Ansiedade de Separação", "F93.0", "309.21", "Transtornos de Ansiedade", "Medo ou ansiedade excessiva quanto à separação de figuras de apego.", False),
    ("Mutismo Seletivo", "F94.0", "312.23", "Transtornos de Ansiedade", "Fala consistentemente ausente em situações sociais específicas apesar de falar em outras.", False),
    ("Fobia Específica", "F40.2", "300.29", "Transtornos de Ansiedade", "Medo ou ansiedade intensa em relação a um objeto ou situação específica.", False),
    ("Transtorno de Ansiedade Social", "F40.1", "300.23", "Transtornos de Ansiedade", "Medo ou ansiedade intensa em situações sociais onde pode ser avaliado.", True),
    ("Transtorno do Pânico", "F41.0", "300.01", "Transtornos de Ansiedade", "Ataques de pânico inesperados recorrentes com preocupação persistente sobre novos ataques.", True),
    ("Agorafobia", "F40.0", "300.22", "Transtornos de Ansiedade", "Medo ou ansiedade intensa em situações onde escapar pode ser difícil.", True),
    ("Transtorno de Ansiedade Generalizada", "F41.1", "300.02", "Transtornos de Ansiedade", "Preocupação excessiva e incontrolável sobre diversos eventos por pelo menos 6 meses.", True),
    ("Transtorno de Ansiedade Induzido por Substância", "F19.180", "292.89", "Transtornos de Ansiedade", "Ansiedade devido aos efeitos de uma substância.", False),
    ("Transtorno de Ansiedade Devido a Outra Condição Médica", "F06.4", "293.84", "Transtornos de Ansiedade", "Ansiedade consequência de outra condição médica.", False),
    ("Outro Transtorno de Ansiedade Especificado", "F41.8", "300.09", "Transtornos de Ansiedade", "Sintomas de ansiedade que não preenchem critérios completos.", False),
    ("Transtorno de Ansiedade Não Especificado", "F41.9", "300.00", "Transtornos de Ansiedade", "Sintomas de ansiedade sem especificação.", False),

    # ── Chapter 6: Transtornos Obsessivo-Compulsivos e Relacionados ──
    ("Transtorno Obsessivo-Compulsivo", "F42.9", "300.3", "Transtornos Obsessivo-Compulsivos e Relacionados", "Obsessões e/ou compulsões que consomem tempo e causam sofrimento.", True),
    ("Transtorno Dismórfico Corporal", "F45.22", "300.7", "Transtornos Obsessivo-Compulsivos e Relacionados", "Preocupação com um ou mais defeitos na aparência física não observáveis.", False),
    ("Transtorno de Acumulação", "F42.3", "300.3", "Transtornos Obsessivo-Compulsivos e Relacionados", "Dificuldade persistente em descartar posses, independentemente do valor real.", False),
    ("Tricotilomania (Transtorno de Arrancar Cabelo)", "F63.3", "312.39", "Transtornos Obsessivo-Compulsivos e Relacionados", "Arrancar cabelos recorrentemente, resultando em perda capilar.", False),
    ("Transtorno de Escoriação (Skin Picking)", "L98.1", "698.4", "Transtornos Obsessivo-Compulsivos e Relacionados", "Beliscar a pele recorrentemente, resultando em lesões cutâneas.", False),
    ("TOC Induzido por Substância", "F19.188", "292.89", "Transtornos Obsessivo-Compulsivos e Relacionados", "Sintomas obsessivo-compulsivos devido aos efeitos de uma substância.", False),
    ("TOC Devido a Outra Condição Médica", "F06.8", "294.8", "Transtornos Obsessivo-Compulsivos e Relacionados", "Sintomas obsessivo-compulsivos consequência de outra condição médica.", False),
    ("Outro Transtorno Obsessivo-Compulsivo Especificado", "F42.8", "300.3", "Transtornos Obsessivo-Compulsivos e Relacionados", "Sintomas obsessivo-compulsivos que não preenchem critérios completos.", False),
    ("Transtorno Obsessivo-Compulsivo Não Especificado", "F42.9", "300.3", "Transtornos Obsessivo-Compulsivos e Relacionados", "Sintomas obsessivo-compulsivos sem especificação.", False),

    # ── Chapter 7: Transtornos Relacionados a Trauma e Estressores ──
    ("Transtorno de Apego Reativo", "F94.1", "313.89", "Transtornos Relacionados a Trauma e Estressores", "Padrão inibido emocionalmente e retraído devido a cuidados extremamente insuficientes.", False),
    ("Transtorno de Engajamento Social Desinibido", "F94.2", "313.89", "Transtornos Relacionados a Trauma e Estressores", "Comportamento excessivamente familiar com estranhos devido a cuidados insuficientes.", False),
    ("Transtorno de Estresse Pós-Traumático", "F43.1", "309.81", "Transtornos Relacionados a Trauma e Estressores", "Reação intensa a evento traumático com revivência, evitação, alterações cognitivas e de humor.", True),
    ("Transtorno de Estresse Agudo", "F43.0", "308.3", "Transtornos Relacionados a Trauma e Estressores", "Reação intensa a evento traumático com duração de 3 dias a 1 mês.", False),
    ("Transtornos de Adaptação", "F43.20", "309.9", "Transtornos Relacionados a Trauma e Estressores", "Sintomas emocionais ou comportamentais em resposta a um estressor identificável.", False),
    ("Transtorno de Luto Prolongado", "F43.8", "309.89", "Transtornos Relacionados a Trauma e Estressores", "Dor intensa e persistente após a morte de alguém próximo por pelo menos 12 meses.", False),
    ("Outro Transtorno Relacionado a Trauma Especificado", "F43.8", "309.89", "Transtornos Relacionados a Trauma e Estressores", "Sintomas relacionados a trauma que não preenchem critérios completos.", False),
    ("Transtorno Relacionado a Trauma Não Especificado", "F43.9", "309.9", "Transtornos Relacionados a Trauma e Estressores", "Sintomas relacionados a trauma sem especificação.", False),

    # ── Chapter 8: Transtornos Dissociativos ──
    ("Transtorno Dissociativo de Identidade", "F44.81", "300.14", "Transtornos Dissociativos", "Perturbação da identidade caracterizada por dois ou mais estados de personalidade distintos.", False),
    ("Amnésia Dissociativa", "F44.0", "300.12", "Transtornos Dissociativos", "Incapacidade de recordar informações autobiográficas, geralmente traumáticas.", False),
    ("Transtorno de Despersonalização/Desrealização", "F48.1", "300.6", "Transtornos Dissociativos", "Experiências persistentes de despersonalização e/ou desrealização.", False),
    ("Outro Transtorno Dissociativo Especificado", "F44.89", "300.15", "Transtornos Dissociativos", "Sintomas dissociativos que não preenchem critérios completos.", False),
    ("Transtorno Dissociativo Não Especificado", "F44.9", "300.15", "Transtornos Dissociativos", "Sintomas dissociativos sem especificação.", False),

    # ── Chapter 9: Transtornos de Sintomas Somáticos e Relacionados ──
    ("Transtorno de Sintomas Somáticos", "F45.1", "300.82", "Transtornos de Sintomas Somáticos e Relacionados", "Um ou mais sintomas somáticos que causam sofrimento com pensamentos e sentimentos excessivos.", True),
    ("Transtorno de Ansiedade de Doença", "F45.21", "300.7", "Transtornos de Sintomas Somáticos e Relacionados", "Preocupação com ter ou adquirir uma doença grave com sintomas somáticos leves ou ausentes.", False),
    ("Transtorno Conversivo (Transtorno de Sintomas Neurológicos Funcionais)", "F44.4-F44.7", "300.11", "Transtornos de Sintomas Somáticos e Relacionados", "Sintomas neurológicos motores ou sensoriais incompatíveis com condições neurológicas.", False),
    ("Transtorno Factício", "F68.1", "300.19", "Transtornos de Sintomas Somáticos e Relacionados", "Falsificação de sinais ou sintomas físicos ou psicológicos com decepção evidente.", False),
    ("Fatores Psicológicos que Afetam Outras Condições Médicas", "F54", "316", "Transtornos de Sintomas Somáticos e Relacionados", "Fatores psicológicos ou comportamentais que afetam adversamente uma condição médica.", False),
    ("Outro Transtorno de Sintomas Somáticos Especificado", "F45.8", "300.89", "Transtornos de Sintomas Somáticos e Relacionados", "Sintomas somáticos que não preenchem critérios completos.", False),
    ("Transtorno de Sintomas Somáticos Não Especificado", "F45.9", "300.82", "Transtornos de Sintomas Somáticos e Relacionados", "Sintomas somáticos sem especificação.", False),

    # ── Chapter 10: Transtornos Alimentares e da Alimentação ──
    ("Pica", "F98.3", "307.52", "Transtornos Alimentares e da Alimentação", "Ingestão persistente de substâncias não nutritivas e não alimentares.", False),
    ("Transtorno de Ruminação", "F98.21", "307.53", "Transtornos Alimentares e da Alimentação", "Regurgitação repetida de alimentos durante pelo menos 1 mês.", False),
    ("Transtorno Alimentar Restritivo-Evitante", "F50.82", "307.59", "Transtornos Alimentares e da Alimentação", "Falta de interesse por comida ou evitação baseada em características sensoriais.", False),
    ("Anorexia Nervosa", "F50.0", "307.1", "Transtornos Alimentares e da Alimentação", "Restrição energética intensa, medo intenso de ganhar peso e perturbação na autoavaliação do peso.", True),
    ("Bulimia Nervosa", "F50.2", "307.51", "Transtornos Alimentares e da Alimentação", "Episódios de compulsão alimentar seguidos de comportamentos compensatórios inadequados.", True),
    ("Transtorno de Compulsão Alimentar", "F50.8", "307.59", "Transtornos Alimentares e da Alimentação", "Episódios recorrentes de compulsão alimentar sem comportamentos compensatórios.", True),
    ("Outro Transtorno Alimentar Especificado", "F50.89", "307.59", "Transtornos Alimentares e da Alimentação", "Sintomas alimentares que não preenchem critérios completos.", False),
    ("Transtorno Alimentar Não Especificado", "F50.9", "307.50", "Transtornos Alimentares e da Alimentação", "Sintomas alimentares sem especificação.", False),

    # ── Chapter 11: Transtornos da Eliminação ──
    ("Enurese", "F98.0", "307.6", "Transtornos da Eliminação", "Eliminação repetida de urina na cama ou roupa.", False),
    ("Encoprese", "F98.1", "307.7", "Transtornos da Eliminação", "Eliminação repetida de fezes em locais inadequados.", False),
    ("Outro Transtorno da Eliminação Especificado", "F98.8", "307.7", "Transtornos da Eliminação", "Sintomas de eliminação que não preenchem critérios completos.", False),
    ("Transtorno da Eliminação Não Especificado", "F98.9", "307.7", "Transtornos da Eliminação", "Sintomas de eliminação sem especificação.", False),

    # ── Chapter 12: Transtornos do Sono-Vigília ──
    ("Transtorno de Insônia", "G47.0", "307.42", "Transtornos do Sono-Vigília", "Dificuldade persistente em iniciar ou manter o sono com prejuízo diurno.", True),
    ("Transtorno de Hipersonolência", "G47.10", "307.44", "Transtornos do Sono-Vigília", "Sonolência excessiva apesar de sono principal prolongado.", False),
    ("Narcolepsia", "G47.419", "347.00", "Transtornos do Sono-Vigília", "Ataques recorrentes de sono irresistível com cataplexia e alucinações hipnagógicas.", False),
    ("Apneia Obstrutiva do Sono", "G47.33", "327.23", "Transtornos do Sono-Vigília", "Pausas respiratórias recorrentes durante o sono devido à obstrução das vias aéreas.", False),
    ("Apneia Central do Sono", "G47.31", "327.21", "Transtornos do Sono-Vigília", "Pausas respiratórias recorrentes sem esforço respiratório.", False),
    ("Transtorno do Ritmo Circadiano do Sono-Vigília", "G47.20", "307.45", "Transtornos do Sono-Vigília", "Padrão persistente de perturbação do sono devido a alteração no sistema circadiano.", False),
    ("Transtorno do Despertar do Sono Não REM (Sonambulismo)", "F51.3", "307.46", "Transtornos do Sono-Vigília", "Episódios de levantar e andar durante o sono de ondas lentas.", False),
    ("Terror Noturno", "F51.4", "307.46", "Transtornos do Sono-Vigília", "Episódios de gritos de medo intenso com despertar parcial.", False),
    ("Transtorno do Pesadelo", "F51.5", "307.47", "Transtornos do Sono-Vigília", "Sonhos extensos, bem lembrados e extremamente disféricos.", False),
    ("Transtorno Comportamental do Sono REM", "G47.52", "327.42", "Transtornos do Sono-Vigília", "Episódios de vocalização e movimentos complexos durante o sono REM.", False),
    ("Síndrome das Pernas Inquietas", "G25.81", "333.94", "Transtornos do Sono-Vigília", "Necessidade urgente de mover as pernas com sensações desconfortáveis.", False),
    ("Transtorno do Sono Induzido por Substância", "F19.182", "292.85", "Transtornos do Sono-Vigília", "Perturbação do sono devido aos efeitos de uma substância.", False),
    ("Outro Transtorno do Sono-Vigília Especificado", "G47.8", "307.49", "Transtornos do Sono-Vigília", "Sintomas do sono que não preenchem critérios completos.", False),
    ("Transtorno do Sono-Vigília Não Especificado", "G47.9", "307.49", "Transtornos do Sono-Vigília", "Sintomas do sono sem especificação.", False),

    # ── Chapter 13: Disfunções Sexuais ──
    ("Ejaculação Retardada", "F52.32", "302.74", "Disfunções Sexuais", "Atraso ou ausência de ejaculação em quase todas as atividades sexuais.", False),
    ("Transtorno Erétil", "F52.21", "302.72", "Disfunções Sexuais", "Dificuldade persistente em obter ou manter ereção.", False),
    ("Transtorno do Orgasmo Feminino", "F52.31", "302.73", "Disfunções Sexuais", "Ausência ou atraso do orgasmo feminino.", False),
    ("Transtorno do Interesse/Excitação Sexual Feminino", "F52.22", "302.72", "Disfunções Sexuais", "Falta ou redução do interesse/excitação sexual feminino.", False),
    ("Transtorno da Dor Gênito-Pélvica/Penetração", "F52.6", "302.76", "Disfunções Sexuais", "Dificuldade persistente com penetração vaginal com dor e ansiedade.", False),
    ("Transtorno do Desejo Sexual Hipoativo Masculino", "F52.0", "302.71", "Disfunções Sexuais", "Déficit ou ausência de desejo/ideação sexual masculino.", False),
    ("Ejaculação Prematura", "F52.4", "302.75", "Disfunções Sexuais", "Ejaculação recorrente antes ou logo após a penetração.", False),
    ("Disfunção Sexual Induzida por Substância", "F19.181", "292.89", "Disfunções Sexuais", "Disfunção sexual devido aos efeitos de uma substância.", False),
    ("Outra Disfunção Sexual Especificada", "F52.8", "302.79", "Disfunções Sexuais", "Disfunção sexual que não preenche critérios completos.", False),
    ("Disfunção Sexual Não Especificada", "F52.9", "302.70", "Disfunções Sexuais", "Disfunção sexual sem especificação.", False),

    # ── Chapter 14: Disforia de Gênero ──
    ("Disforia de Gênero em Crianças", "F64.2", "302.6", "Disforia de Gênero", "Incongruência entre o gênero experienciado e o gênero designado em crianças.", False),
    ("Disforia de Gênero em Adolescentes e Adultos", "F64.1", "302.85", "Disforia de Gênero", "Incongruência entre o gênero experienciado e o gênero designado em adolescentes/adultos.", False),
    ("Outra Disforia de Gênero Especificada", "F64.8", "302.6", "Disforia de Gênero", "Disforia de gênero que não preenche critérios completos.", False),
    ("Disforia de Gênero Não Especificada", "F64.9", "302.6", "Disforia de Gênero", "Disforia de gênero sem especificação.", False),

    # ── Chapter 15: Transtornos Disruptivos, do Controle de Impulsos e da Conduta ──
    ("Transtorno Opositivo-Desafiador", "F91.3", "313.81", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Padrão de humor raivoso/irritável, comportamento questionador e vingativo.", False),
    ("Transtorno Explosivo Intermitente", "F63.81", "312.34", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Explosões comportamentais impulsivas e agressivas desproporcionais.", False),
    ("Transtorno da Conduta", "F91.8", "312.82", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Padrão repetitivo de comportamento que viola direitos básicos dos outros.", False),
    ("Transtorno da Personalidade Antissocial", "F60.2", "301.7", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Padrão de desrespeito e violação dos direitos dos outros desde os 15 anos.", False),
    ("Piromania", "F63.1", "312.33", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Incêndio deliberado e proposital com tensão antes do ato.", False),
    ("Cleptomania", "F63.2", "312.32", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Falha recorrente em resistir a impulsos de furtar objetos desnecessários.", False),
    ("Outro Transtorno Disruptivo Especificado", "F91.8", "312.89", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Sintomas disruptivos que não preenchem critérios completos.", False),
    ("Transtorno Disruptivo Não Especificado", "F91.9", "312.9", "Transtornos Disruptivos, do Controle de Impulsos e da Conduta", "Sintomas disruptivos sem especificação.", False),

    # ── Chapter 16: Transtornos Relacionados a Substâncias e Aditivos ──
    ("Transtorno por Uso de Substâncias", "F19.20", "304.90", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de substâncias com prejuízo clinicamente significativo.", True),
    ("Transtorno por Uso de Álcool", "F10.20", "303.90", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de álcool causando prejuízo.", False),
    ("Intoxicação Alcoólica", "F10.129", "303.00", "Transtornos Relacionados a Substâncias e Aditivos", "Sintomas reversíveis específicos devido à ingestão recente de álcool.", False),
    ("Abstinência Alcoólica", "F10.239", "291.81", "Transtornos Relacionados a Substâncias e Aditivos", "Sintomas específicos após cessação ou redução do uso de álcool.", False),
    ("Transtorno por Uso de Cannabis", "F12.20", "304.30", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de cannabis causando prejuízo.", False),
    ("Transtorno por Uso de Alucinógenos", "F16.20", "304.50", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de alucinógenos causando prejuízo.", False),
    ("Transtorno por Uso de Inalantes", "F18.20", "304.60", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de inalantes causando prejuízo.", False),
    ("Transtorno por Uso de Opioides", "F11.20", "304.00", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de opioides causando prejuízo.", False),
    ("Transtorno por Uso de Sedativos/Hipnóticos/Ansiolíticos", "F13.20", "304.10", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de sedativos causando prejuízo.", False),
    ("Transtorno por Uso de Estimulantes", "F15.20", "304.40", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de estimulantes causando prejuízo.", False),
    ("Transtorno por Uso de Tabaco", "F17.200", "305.1", "Transtornos Relacionados a Substâncias e Aditivos", "Padrão problemático de uso de tabaco causando prejuízo.", False),
    ("Transtorno do Jogo (Jogo Patológico)", "Z72.0", "312.31", "Transtornos Relacionados a Substâncias e Aditivos", "Comportamento problemático de jogo persistente e recorrente.", False),

    # ── Chapter 17: Transtornos Neurocognitivos ──
    ("Delirium", "F05", "293.0", "Transtornos Neurocognitivos", "Perturbação da atenção e consciência com desenvolvimento agudo.", False),
    ("Transtorno Neurocognitivo Maior — Doença de Alzheimer", "G30.9", "331.0", "Transtornos Neurocognitivos", "Declínio cognitivo significativo devido à doença de Alzheimer.", False),
    ("Transtorno Neurocognitivo Maior — Degeneração Lobar Frontotemporal", "G31.09", "331.19", "Transtornos Neurocognitivos", "Declínio cognitivo devido à DFT com alterações comportamentais ou linguagem.", False),
    ("Transtorno Neurocognitivo Maior — Corpos de Lewy", "G31.83", "331.82", "Transtornos Neurocognitivos", "Declínio cognitivo com flutuações, alucinações visuais e parkinsonismo.", False),
    ("Transtorno Neurocognitivo Maior — Vascular", "F01.50", "290.40", "Transtornos Neurocognitivos", "Declínio cognitivo devido a doença cerebrovascular.", False),
    ("Transtorno Neurocognitivo Maior — Traumatismo Cranioencefálico", "S06.9", "907.0", "Transtornos Neurocognitivos", "Declínio cognitivo devido a lesão cerebral traumática.", False),
    ("Transtorno Neurocognitivo Leve", "G31.84", "331.83", "Transtornos Neurocognitivos", "Declínio cognitivo modesto sem interferência na independência.", False),
    ("Outro Transtorno Neurocognitivo Especificado", "F06.8", "294.8", "Transtornos Neurocognitivos", "Declínio cognitivo que não preenche critérios completos.", False),
    ("Transtorno Neurocognitivo Não Especificado", "F06.9", "294.9", "Transtornos Neurocognitivos", "Declínio cognitivo sem especificação.", False),

    # ── Chapter 18: Transtornos da Personalidade ──
    ("Transtorno da Personalidade Paranoide", "F60.0", "301.0", "Transtornos da Personalidade", "Desconfiança e suspeita generalizadas em relação aos outros.", False),
    ("Transtorno da Personalidade Esquizoide", "F60.1", "301.20", "Transtornos da Personalidade", "Padrão de distanciamento das relações sociais e afetividade restrita.", False),
    ("Transtorno da Personalidade Esquizotípica", "F21", "301.22", "Transtornos da Personalidade", "Déficits sociais e interpessoais com distorções cognitivo-perceptivas.", False),
    ("Transtorno da Personalidade Antissocial", "F60.2", "301.7", "Transtornos da Personalidade", "Padrão de desrespeito e violação dos direitos dos outros.", False),
    ("Transtorno da Personalidade Borderline", "F60.3", "301.83", "Transtornos da Personalidade", "Instabilidade nos relacionamentos, autoimagem e afetos com impulsividade.", False),
    ("Transtorno da Personalidade Histriônica", "F60.4", "301.50", "Transtornos da Personalidade", "Emocionalidade e busca de atenção excessivas.", False),
    ("Transtorno da Personalidade Narcisista", "F60.81", "301.81", "Transtornos da Personalidade", "Padrão de grandiosidade, necessidade de admiração e falta de empatia.", False),
    ("Transtorno da Personalidade Esquiva", "F60.6", "301.82", "Transtornos da Personalidade", "Inibição social, sentimentos de inadequação e hipersensibilidade a avaliação negativa.", False),
    ("Transtorno da Personalidade Dependente", "F60.7", "301.6", "Transtornos da Personalidade", "Necessidade excessiva de ser cuidado com comportamento submisso.", False),
    ("Transtorno da Personalidade Obsessivo-Compulsiva", "F60.5", "301.4", "Transtornos da Personalidade", "Preocupação com ordem, perfeccionismo e controle.", False),
    ("Outro Transtorno da Personalidade Especificado", "F60.89", "301.89", "Transtornos da Personalidade", "Padrão de personalidade que não preenche critérios completos.", False),
    ("Transtorno da Personalidade Não Especificado", "F60.9", "301.9", "Transtornos da Personalidade", "Transtorno da personalidade sem especificação.", False),

    # ── Chapter 19: Transtornos Parafílicos ──
    ("Transtorno Voyeurista", "F65.3", "302.82", "Transtornos Parafílicos", "Excitação sexual intensa ao observar pessoas nuas ou em atividade sexual.", False),
    ("Transtorno Exhibitionista", "F65.2", "302.4", "Transtornos Parafílicos", "Excitação sexual intensa pela exposição dos próprios genitais.", False),
    ("Transtorno Frotteurista", "F65.81", "302.89", "Transtornos Parafílicos", "Excitação sexual intensa ao tocar ou esfregar-se em pessoa não consentinte.", False),
    ("Transtorno de Masoquismo Sexual", "F65.51", "302.83", "Transtornos Parafílicos", "Excitação sexual intensa ao ser humilhado ou fazer sofrer.", False),
    ("Transtorno de Sadismo Sexual", "F65.52", "302.84", "Transtornos Parafílicos", "Excitação sexual intensa pelo sofrimento físico ou psicológico de outra pessoa.", False),
    ("Transtorno Pedofílico", "F65.4", "302.2", "Transtornos Parafílicos", "Excitação sexual intensa por crianças pré-púberes.", False),
    ("Transtorno Fetichista", "F65.0", "302.81", "Transtornos Parafílicos", "Excitação sexual intensa pelo uso de objetos inanimados.", False),
    ("Transtorno Transvéstico", "F65.1", "302.3", "Transtornos Parafílicos", "Excitação sexual intensa ao usar roupas do sexo oposto.", False),
    ("Outro Transtorno Parafílico Especificado", "F65.89", "302.89", "Transtornos Parafílicos", "Interesse parafílico que não preenche critérios completos.", False),
    ("Transtorno Parafílico Não Especificado", "F65.9", "302.9", "Transtornos Parafílicos", "Interesse parafílico sem especificação.", False),

    # ── Chapter 20: Outros Transtornos Mentais ──
    ("Outro Transtorno Mental Especificado", "F99", "300.9", "Outros Transtornos Mentais", "Sintomas de transtorno mental que não preenchem critérios para transtorno específico.", False),
    ("Transtorno Mental Não Especificado", "F99", "300.9", "Outros Transtornos Mentais", "Sintomas de transtorno mental sem especificação.", False),
]

# Map of chapter names for frontend display
CHAPTER_PT = {
    "Transtornos do Neurodesenvolvimento": "Transtornos do Neurodesenvolvimento",
    "Espectro da Esquizofrenia e Outros Transtornos Psicóticos": "Espectro da Esquizofrenia e Outros Transtornos Psicóticos",
    "Transtornos Bipolares e Relacionados": "Transtornos Bipolares e Relacionados",
    "Transtornos Depressivos": "Transtornos Depressivos",
    "Transtornos de Ansiedade": "Transtornos de Ansiedade",
    "Transtornos Obsessivo-Compulsivos e Relacionados": "Transtornos Obsessivo-Compulsivos e Relacionados",
    "Transtornos Relacionados a Trauma e Estressores": "Transtornos Relacionados a Trauma e Estressores",
    "Transtornos Dissociativos": "Transtornos Dissociativos",
    "Transtornos de Sintomas Somáticos e Relacionados": "Transtornos de Sintomas Somáticos e Relacionados",
    "Transtornos Alimentares e da Alimentação": "Transtornos Alimentares e da Alimentação",
    "Transtornos da Eliminação": "Transtornos da Eliminação",
    "Transtornos do Sono-Vigília": "Transtornos do Sono-Vigília",
    "Disfunções Sexuais": "Disfunções Sexuais",
    "Disforia de Gênero": "Disforia de Gênero",
    "Transtornos Disruptivos, do Controle de Impulsos e da Conduta": "Transtornos Disruptivos, do Controle de Impulsos e da Conduta",
    "Transtornos Relacionados a Substâncias e Aditivos": "Transtornos Relacionados a Substâncias e Aditivos",
    "Transtornos Neurocognitivos": "Transtornos Neurocognitivos",
    "Transtornos da Personalidade": "Transtornos da Personalidade",
    "Transtornos Parafílicos": "Transtornos Parafílicos",
    "Outros Transtornos Mentais": "Outros Transtornos Mentais",
}

CHAPTER_ORDER = [
    "Transtornos do Neurodesenvolvimento",
    "Espectro da Esquizofrenia e Outros Transtornos Psicóticos",
    "Transtornos Bipolares e Relacionados",
    "Transtornos Depressivos",
    "Transtornos de Ansiedade",
    "Transtornos Obsessivo-Compulsivos e Relacionados",
    "Transtornos Relacionados a Trauma e Estressores",
    "Transtornos Dissociativos",
    "Transtornos de Sintomas Somáticos e Relacionados",
    "Transtornos Alimentares e da Alimentação",
    "Transtornos da Eliminação",
    "Transtornos do Sono-Vigília",
    "Disfunções Sexuais",
    "Disforia de Gênero",
    "Transtornos Disruptivos, do Controle de Impulsos e da Conduta",
    "Transtornos Relacionados a Substâncias e Aditivos",
    "Transtornos Neurocognitivos",
    "Transtornos da Personalidade",
    "Transtornos Parafílicos",
    "Outros Transtornos Mentais",
]

# Core disorders (19) with full clinical pipeline — for quick lookup
CORE_DISORDER_NAMES = {
    "Transtorno Depressivo Maior",
    "Transtorno de Ansiedade Generalizada",
    "Transtorno do Pânico",
    "Transtorno de Estresse Pós-Traumático",
    "Transtorno Depressivo Persistente (Distimia)",
    "Transtorno de Ansiedade Social",
    "Transtorno Bipolar Tipo I",
    "Transtorno Bipolar Tipo II",
    "Transtorno Obsessivo-Compulsivo",
    "Agorafobia",
    "Transtorno por Uso de Substâncias",
    "Anorexia Nervosa",
    "Bulimia Nervosa",
    "Transtorno de Compulsão Alimentar",
    "Transtorno de Insônia",
    "Esquizofrenia / Transtorno Psicótico",
    "Transtorno de Sintomas Somáticos",
    "Transtorno do Espectro Autista",
    "Transtorno de Déficit de Atenção/Hiperatividade",
}
